<script lang="ts" setup></script>

<template>
    <nav>
        <div class="side-menu">
            <ul class="side-menu-items">
                <li>
                    <img width="40" src="../../../assets/img/logos/fitness-logo-and-gym-icon-design-illustrationicon-free-vector.png" alt="">
                </li>
            </ul>
        </div>
    </nav>
</template>

<style>
@import "/src/assets/css/components/menu-components/side-dash-nav.css";
</style>