<script lang="ts" setup>

</script>

<template>
    <nav>
        <div class="side-menu">
            <ul class="side-menu-items">
                <li class="menu-item logo">
                    <img width="40" src="../../../assets/img/logos/fitness-logo-and-gym-icon-design-illustrationicon-free-vector.png" alt="">
                </li>
                <li class="menu-item home">
                    <img width="25" src="../../../assets/img/logos/training.png" alt="">
                </li>
                <li class="menu-item analytics">
                    <img width="25" src="../../../assets/img/logos/analitics.png" alt="">
                </li>
                <li class="menu-item logout">
                    <img width="25" src="../../../assets/img/logos/log-out.png" alt="">
                </li>
            </ul>
        </div>
    </nav>
</template>

<style>
@import "/src/assets/css/components/menu-components/side-dash-nav.css";
</style>